    extern puts
    extern SDL_Init
    extern SDL_Quit
    extern SDL_CreateWindow
    extern SDL_CreateRenderer
    extern SDL_DestroyWindow
    extern SDL_DestroyRenderer
    extern SDL_RenderClear
    extern SDL_RenderPresent
    extern SDL_SetRenderDrawColor
    extern SDL_PollEvent